[package]
name = "nexusrust"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-cors = "0.7.0"


# [workspace]
# members = ["ne", "nexus_frontend"]

[[bin]]
name = "nexusrust"
path = "src/main.rs"
