# Generated by Django 5.0.6 on 2024-06-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='deaprtment',
            new_name='department',
        ),
    ]
