# Generated by Django 5.0.6 on 2024-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0004_remove_userprofile_user_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(default='default_organization', max_length=255),
        ),
    ]
